config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user

  def self.search_by(search_term)
  where("price LIKE :search_term", search_term: "%#{search_term.downcase}%")
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    return self.email.split('@')[0].capitalize
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                  length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  around_action :switch_locale

  protected

    def switch_locale(&action)
      lang = params[:lang] || session[:lang] || I18n.default_locale
      session[:lang] = params[:lang] if params[:lang]
      I18n.with_locale(lang, &action)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
    if params[:search]
    @search_term = params[:search]
    @bookings = @bookings.search_by(@search_term)
  end
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully Deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:price, :duration, :room, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    redirect_to root_path, warning: "You are not authorized" unless @user = current_user
    @user = User.find(params[:id])
    @user_bookings = @user.bookings
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :price %>
  <%= form.text_area :price %>
</div>

<div class="field">
  <%= form.label :duration %>
  <%= form.text_area :duration %>
</div>

<div class="field">
  <%= form.label :room %>
  <%= form.text_area :room %>
</div>

<div class="field">
  <%= form.label :location %>
  <%= form.text_area :location %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"></p>

<h1>Bookings</h1>
<table>
  <thead>
    <tr>
      <th>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspPrice</th>
      <th>&nbsp&nbspDuration</th>
      <th>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspRoom</th>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <h2>Search</h2>
  <div class="searchingclass">
    <form class="search"
    <%= form_for "", url: bookings_path, role: "search", method: :get do %>
    <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
    <%= submit_tag "Search" %>
    <% end %>
    </form>
  </div>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.price %></td>
        <td><%= booking.duration %></td>
        <td><%= booking.room %></td>
        <td><%= booking.location %></td>
        <td><%= booking.user_id %></td>
        <td><%= link_to 'Show', booking %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <td><%= link_to 'New Booking', new_booking_path %></td>
  </tbody>
</table>

<br>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Booking Information</h2>

<p class="main">
  <strong>Price:</strong>
  <%= @booking.price %>
</p>

<p class="main">
  <strong>Duration:</strong>
  <%= @booking.duration %>
</p>

<p class="main">
  <strong>Room:</strong>
  <%= @booking.room %>
</p>

<p class="main">
  <strong>Location:</strong>
  <%= @booking.location %>
</p>

<p class="main">
  <strong>User:</strong>
  <%= @booking.user.username %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/_navigationbar.html.erb
<nav>
    <div class="navigation">
        <% if user_signed_in? %>
        <div class="nav-links">
          <%= link_to t('navbar.home'), root_path %>
          <%= link_to t( 'navigation.Bookings'), bookings_path %>
          <%= link_to 'ENG', '?lang=en' %>
          <%= link_to 'ES', '?lang=es' %>
        </div>
        <% end %>

        <% if user_signed_in? %>
      <div class="user-login">
            <%= t('navbar.welcome', name: current_user.username) %>
            <%= link_to t('navigation.Sign out'), destroy_user_session_path, method: :delete %>
        </div>
        <% else %>
      <div class="nav-links">
          <%= link_to t('navbar.home'), root_path %>
     </div>

     <div class="user-login">
       <%= link_to t('navigation.Sign in'), new_user_session_path %>
       <%= link_to t('navigation.Sign up'), new_user_registration_path %>
       <% end %>

     </div>
     </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/navigationbar' %>
     <div>
       <<% if notice %>
   <p class="alert alert-success"><%= notice %></p>
 <% end %>
 <% if alert %>
   <p class="alert alert-danger"><%= alert %></p>
 <% end %>
     </div>
     <div class="ui container body-container">

       <%= yield %>
     </div>
   </body>
</html>

app/views/pages/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<body>
  <div class="jumbotron">
    <% if user_signed_in? %>
      <h1>Welcome back <%= current_user.username %></h1>
      <p class="lead">
        You are signed in! You can make a booking by clicking the red link below!
      </p>
      <%= link_to 'Bookings', bookings_path, :class => 'btn btn-large btn-danger' %>
    <% else %>
      <h1>Welcome, new user!</h1>
      <p class="lead">
        You must sign in or sign up before you can access my ruby on rails designed website!
        You can however view current bookings, but you won't be able to make your own without an account!
      </p>
      <div class="row-fluid">
        <div class="span6">
          <%= link_to 'Bookings', bookings_path, :class => 'btn btn-large btn-danger' %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <iframe class="iframe_style" src="https://www.trivago.ie/" style="width: 100%;height:2000px"></iframe>
  </div>

</body>